travis:
  secure:
    BINSTAR_TOKEN: ua8B5pZ5aN6+0BSx83vMIEr2VAqa7HwZG3zoI25n1dLTVefJZkAlZOuNPVZOkYXeYp2eS6Oztpkdn/lsM+JP6Ny+N5noT5PltwHwN4LB/q8mwGerpKCcGDRULKp/SJ9ktQFNs52O2Lz8uVPsb+ruUSgDW8JsmHz2W5L+N6zIbGH54xq/9mfIepyXeALajCmXHVz3Vx5FSEYNGuDV90l4cn+/vMBVO2wNkLSlBCUKiF409i240h+uu4GqufNDyxCc6WVMgyLChN+YrnnAtiUbpn+XmNjk02yuRj0BBZ3bpA/lyTQ7Jn1625B39cuVEa9IEYzKCKdJzu5WX3GJORfnaqM1vtNnGmajYee6ZGbSgwQue0l9L9jXaW1VsfoYFovJBDtFIAhjtDIwr1SWx2/IGW2ljP8aspfC22qRSRTF9/ZF9vIf+v/aOMWG+rfVsaKo7J/F3+di3ntJl81vTI90HabzuaPHWtLKkgdYxb0749XwJGXGo9HIH6Cnl+AWgYhfFs/qhJcXQl5UXHgwqNewfM0F8AvuEUvmyEzVz0jqxto3rF6/Afe+9ZfGL4Jz/vl28mWAhAFj6022oWDRzurJUNEtG3aAiNbjnT8aDlNMnn3moZ7xkjyH16dB6M+8MwLNXHD73oxtzo3GvGfkKbWpAnhGgeTRDZO4ysLPm3xB870=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
